# Generated by Django 4.2.16 on 2025-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ROLE',
                'managed': False,
            },
        ),
    ]
