# Generated by Django 4.2.16 on 2025-02-21 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_report', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField()),
                ('cpu_speed', models.FloatField()),
                ('cpu_cores', models.IntegerField()),
                ('cpu_logical', models.IntegerField()),
                ('cpu_sockets', models.IntegerField()),
                ('ram_used', models.FloatField()),
                ('ram_total', models.FloatField()),
                ('net_upload', models.FloatField()),
                ('net_download', models.FloatField()),
                ('disk_used', models.FloatField()),
                ('disk_total', models.FloatField()),
            ],
            options={
                'db_table': 'REPORT',
                'managed': False,
            },
        ),
    ]
