# Generated by Django 4.2.16 on 2025-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id_alert', models.AutoField(primary_key=True, serialize=False)),
                ('description_alerts', models.TextField(db_column='DESCRIPTION_ALERTS')),
                ('timestamp_alerts', models.CharField(db_column='TIMESTAMP_ALERTS', max_length=50)),
                ('alert_location', models.CharField(db_column='ALERT_LOCATION', max_length=255)),
            ],
            options={
                'db_table': 'ALERTS',
                'managed': False,
            },
        ),
    ]
