# Generated by Django 5.1.6 on 2025-02-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('cpu_speed', models.FloatField()),
                ('cpu_model', models.CharField(max_length=255)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_logical', models.IntegerField()),
                ('ram_total', models.FloatField()),
                ('ram_used', models.FloatField()),
                ('net_upload', models.FloatField()),
                ('net_download', models.FloatField()),
                ('disk_total', models.FloatField()),
                ('disk_used', models.FloatField()),
            ],
        ),
    ]
